version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: laravel-nginx-upload
    ports:
      - '8001:80'
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: curotec-file-uploading-service-app
    user: '${UID:-1000}:${GID:-1000}'
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - '9001:9000'
    environment:
      - NODE_OPTIONS=--max-old-space-size=8192
    networks:
      - default
  postgres:
    image: postgres:15
    container_name: laravel-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: curotec
      POSTGRES_USER: curotec
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  node:
    image: node:18
    container_name: laravel-node-upload
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    tty: true
    ports:
      - '5173:5173'
    networks:
      - default
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - default

  ngrok:
    image: ngrok/ngrok:latest
    container_name: laravel-ngrok
    ports:
      - '8040:4040' # Changed from 4040:4040
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http nginx:80
    networks:
      - default
    depends_on:
      - nginx

volumes:
  postgres_data:
  pgadmin_data:
